<?php
/**
 * Implements hook_menu().
 */

 function my_theming_menu(){
 	$items['theming'] = array(
 	'title' => 'Theming example',
 	'page callback' => 'theming_page',
 	'access callback' => TRUE
 	);
 	return $items;
 }

/**
* Implements hook_theme().
*/

function my_theming_theme(){
	return array(
		'custom_template' => array(
			'variables' => array(
				'body' => NULL,
				'title' => NULL,
				),
			'template' => 'custom_template',
			),
		);
}

/**
 * theming_page content
*/

function theming_page(){
	//theme_item_list
	$item = array('item 1','item 2','item 3',);
	$title = 'Theme item list Example';
	$type = 'ol';
	$attributes = array('class' => 'newclass');
	 $list =theme_item_list(array('items' => $item, 'title' => $title, 'type' => $type, 'attributes' => $attributes));
	//field set
	drupal_add_library('system', 'drupal.collapse');
	$edit = array(
		'#title' => t('Title'),
		'#children' => t('Text Text Text Text Text Text Text '),
		'#collapsible' => true,
		'#collapsed' => true,
		'#attributes'  => array('class' => array('collapsible', 'collapsed')), 
		);
	 $fieldset = theme('fieldset', array('element' => $edit));
	 //theme_table
	 $header = array(array('data' => t('header1')),
	 				 array('data' => t('header2')),
	 				 array('data' => t('header3'))
	 				 );

	 $rows [] = array(  array('data' => t('row1')),
	 				 array('data' => t('row2')),
	 				 array('data' => t('row3'))
	 				 );

	 $rows [] = array(  array('data' => t('row4')),
	 				 array('data' => t('row5')),
	 				 array('data' => t('row6'))
	 				 );
	 $table = theme('table', array('header' => $header, 'rows' => $rows));
	 //theme image
	 $variables = array(
	 	'path' => 'http://qnimate.com/wp-content/uploads/2014/03/images2.jpg',
	    'alt' => 'Image',
	 	'title' => 'Image',
	 	'wight' => '100%',
	 	'height' => '225px',
	 	'attributes' => array('class' => 'some-img', 'id' => 'my-img'),
	 	);
	 $img = theme('image', $variables);
	 //hook_theme
	 $ctemplate = theme('custom_template', array('body' => 'Text Strong', 'title' => 'Title h2'));

	 return $list . $fieldset . $table . $img . $ctemplate;

}

/**
*
*/

function theme_custom_template($variables){
	$output = '<div class="custom-template-wrapper">';
	$output .=  '<strong class="body">';
	$output .=      $variables['body'];
	$output .=   '</strong>';
	$output .=   '<h2 class="title">';
	$output .=	    $variables['title'];
	$output .=	 '</h2>';
	$output .= '</div>';
	return $output;
}
