<?php

/**
 * Implements hook_menu().
 */
 function mymodule_menu(){
 	$items['main-page'] = array(
 	'title' => 'Main page',
 	'page callback' => 'mymodule_page',
 	'access callback' => TRUE,
 	'manu_name' => 'main-menu'
 	);
 	$items['access-denied'] = array(
 	'title' => 'Access denied',
 	'page callback' => 'mymodule_access_page',
 	'access callback' => FALSE
 	);
 	$items['not-found'] = array(
 	'title' => 'Page not found',
 	'page callback' => 'mymodule_found_page',
 	'access callback' => FALSE
 	);
 	return $items;
 }

/**
 * mymodule_page content
*/
 function mymodule_page(){
 	return t('I main page');
 }

 function mymodule_access_page(){
 	return t('');
 }

 function mymodule_found_page(){
 	return t('');
 }

 /**
 *	Implements hook_block_info
 */

 function mymodule_block_info(){
 	$blocks['message'] = array(
 	'info' => t('Message'),
 	'visibility' => BLOCK_VISIBILITY_NOTLISTED
 	);
 	return $blocks;
 }

/**
* Implements hook_block_view
* Generate title and content
*/

 function mymodule_block_view($delta = ''){
 	$block = array();

 	if($delta == 'message'){
 		$block['subject'] = t('Message');
 		if(user_access('view block example')){
 			$block['content'] = t('Hello i block');
 		}else{
 			$block['content'] = t('access to view this content is denied.');
 		}
 	}

 	return $block;
 }

 /**
* Implements hook_permission
**/

function mymodule_permission(){
	return array('view block example' => array(
	 	'title' => t('Block access'),
	 	'description' => t('Block access description'),
		),
	);
}
